version: '3.9'

services:
  mbd-menu-postgres-db:
    image: postgres:16
    container_name: mbd-postgres
    networks:
      - mbd-bridge
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mbd_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass@SecurE
    volumes:
      - pgdata:/var/lib/postgresql/data

  mbd-rabbitmq:
    image: rabbitmq:3-management
    container_name: mbd-rabbitmq
    networks:
      - mbd-bridge
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

volumes:
  mongodata:
    driver: local
  rabbitmqdata:
    driver: local
  pgdata:
    driver: local

networks:
  mbd-bridge:
    driver: bridge