server:
  port: ${PORT:8200}
  servlet.context-path: /mbd/rest/

spring:
  application:
    name: mbd-auth

  datasource:
    url: ${DATABASE_HOST:jdbc:postgresql://localhost:5433/mbd_auth?currentSchema=dev}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:pass@SecurE}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: dev

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_schema: dev
    show-sql: true

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    management_port: ${RABBIT_MQ_MANAGEMENT_PORT:15672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    virtual-host: /

    prefix: ${spring.application.name}
    exchange:
      - name: default.exchange
        type: fanout
        queues:
          - name: debug-queue
            ttl: 300000
        bindings:
          - queue: debug-queue
            exchange: default.exchange
            routingKey: "#"

springdoc:
  override-with-generic-response: false

logging:
  level:
    root: INFO
    com.mbd: DEBUG
    com.mbd.core.amqp: INFO
    org.flywaydb: INFO
